######################################################################################################
###This configuration file contains all the possible syslogd-sa directives (with default settings).###
###      Each bloc is specific to an application component (buffer, file, network,...)             ###
######################################################################################################
# General default configuration: 
#	1 = enabled
#	0 = disabled 
#fdaemonize_enable: exec application in background
# ffile_enable : enable/disable file 
# fnet_enable : enable/disable net
# fnet_console: enable/disable console
general.fdaemonize_enable=1
general.ffile_enable=1
general.fnet_enable=1
general.console=1
#default logmask (must be in decimal)
default.logmask=64
# Default Buffer configuration (nbrmsgmax: nbr max of message; sizemsgmax: size max of message)
buffer.nbrmsgmax=100
buffer.sizemsgmax=4000 
# Default file configuration (file.logfile: name of file; file.filesize : size of file)
file.logfile=/var/log/syslogdlog.log
file.filesize=500000
# Default net configuration (net.addr: destination address)
net.addr=192.168.1.10
# Default console configuration (console.consolefile : console configuration)
console.consolefile=/dev/console

